# Generated by Django 5.2.8 on 2025-11-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_article_publish_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, max_length=64, verbose_name='Текст в кнопке')),
                ('image', models.ImageField(blank=True, upload_to='partnership/images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Форма участия',
                'verbose_name_plural': 'Формы участия',
            },
        ),
    ]
